language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm test
  - unset CI
  - npm run build
  - set CI

deploy:
  - provider: script
    script: scripts/deploy-now.sh staging
    on:
      branch: develop


notifications:
  slack:
    secure: R4F/Oh+HIp2OWyQ1fTwTRZQEKBhyr4VIexvxTuYuQtzgGcwifw22IeDaBirV9a5vOgheUddHulgFxOKC8bJaS3EUZvIfprVEgATjB2yZqKbiVqRrRbuV+d3+MrhpCsCTAg40pCYeBkzM7T/PyNCQ9XalftZuXhJmdokE+ch2ff1eOUTeGGvnS/ypDa7zY5YNLtrHFBD8TgInr6oqwkkvtxYK8N5sx9TlrhstuLTWh0iww8CHUEkieC/72dxkvahhZlC8U8y2ICycC6w782teMxxcbAKnndMMLH1Q6rDXJ8S2yNO2ywAF2DlM9QWLKJeoAVoZpjx2Ujoy0Xu2dK+KSGcgHbyAnmVQijvUzAMv+gycJDQhvuXaUJzLnn2o8fjNVnm6zgCISmwifXNtxWT8lSyRKE5Rb+XE2tlk3yZXeU9zHdX5PRsJzAxixOSSOtPJdl4p09GrMVVMw08UtPBMOcmVtlaRbCGfhATdiwJxjTOaKlDa4XmhGryaF5v8bO9yzQpWTny6A5av1sRcgoF2+OWVgvANGRfk05QXjuVHRu+oAihiZqfXldSX8oYw90gDwIu2XVvLUBUPCGECLkS1QBOy5LDRafLiGkhtt2ryLjuUn4sT+pvM5o6IUaL86SYljnS/v/fF7CWpHArlelrcXDGwhUMpmFNTPP2gLj9lqnk=


env:
  global:
    secure: z8qu6SigR4jpB7+YQcd9oUFC54tGKtA8ibVlrBZyqVc6t4ZXkQYLcykLGXpET2kcqiiwIpoZv3AelOMjIbVaYs0KBctIEamHvAEaiMxyjNN5SonyWWUjDq5p8+hENRLhEEn62CXvemVYrxQFBuEu1ozz0gdMyI0TI9fb58MHydoAQwb6X6p/gSr36T7MAMsuge4/1eoxL8QvAYuSOs/E6SOSbjTIkJ/c5sdhQcKfG200w9D8eyRp/6WQ9EUVQ42u/Sp0RQRwBVzDUkuM/+ND7bvGSwbTLroGmi5O/Hi70UlMxRtRBvzTeo9XXupEc5zSYwL6jBrJmpVl6BQE35VHIO6C6ELcGY5i2aRUrS2E/h7a+0P7l8px/q7+OTJGwinezdEed0us8+nwwAoQYzCpZarrDMcGYCC2Mi85brxsB15Te6FfYK5CDcTfAwrfHFO3oF16KO4Dy0dSGFguDmnvZCU+BdTtoic5E0+A6HqDPOkYyeiDfUGtlC2xQsQmOxu91fwrYpWNpkx97IEd94g801M4qzmKJy8TO6uIRzD6ts4uwU7q9gDeTat1RgpczAKnXBu8N3Aofk047B7nm1AlW/8ONh1yxDgPvYwakQF9UfezMcsCYDU/27fjNSAYNhymnk3T7aY55oXeH9w10VLfSyh9pIFbQUksX8F2TIxHjo8=
